-- Schema for PostgreSQL (Supabase)
-- Generated for Task Manager migration

-- Users Table
CREATE TABLE IF NOT EXISTS usuarios (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Default User (Note: ON CONFLICT for idempotency)
INSERT INTO usuarios (id, nombre, email, password_hash) 
VALUES (1, 'Usuario Default', 'default@taskmanager.local', 'no-auth')
ON CONFLICT (id) DO NOTHING;

-- Tasks Table
CREATE TABLE IF NOT EXISTS tareas (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INT DEFAULT 1,
    titulo VARCHAR(200) NOT NULL,
    descripcion TEXT,
    fecha_limite DATE,
    -- PostgreSQL doesn't have ENUM in the same way, using VARCHAR with Check constraints is safer for simple apps, or just VARCHAR
    prioridad VARCHAR(20) DEFAULT 'Media',
    estado VARCHAR(20) DEFAULT 'Pendiente',
    categoria VARCHAR(50) DEFAULT 'Otros',
    recordatorio_especial BOOLEAN DEFAULT FALSE,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    responsable VARCHAR(100) DEFAULT 'Cache',
    fecha_completada TIMESTAMP,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);
